"""Extracts the Strengthen Immunity tree's layout from the design canvas.

The canvas's Tree artboard (docs/ui-concepts/canvas/project/Tree.dc.html)
places all 75 nodes of the tree by hand, as a lymphatic system: five tower
columns growing up from a lymph-node hub, core upgrades around the hub, and
the four abilities in the corners, joined by vessels. This script writes that
placement to assets/ui/tree_layout.json, which the game's tree screen
(src/ui/front/TreeScreen) draws from, so the screen is exactly what was
designed and re-running it after the canvas changes refreshes it.

Output, in canvas pixels (a 1920x1080 frame):
  nodes   game key -> centre, diameter, and the glyph icon it shows
  vessels in draw order: SVG path data, wall and lumen widths, the node whose
          ownership lights the lumen (none = always lit), a flowing dash
  labels  pills: root and ability names; capstone name plus branch points
  hub     centre and scale of the lymph node drawing (icon tree_hub.svg)

Node keys are the game's (game/meta/ImmunityTree.cpp); the canvas spells the
same keys with '_' for '.'.

Usage:  python tools/extract_tree_layout.py [--check]
  --check  fail (exit 1) if the committed layout differs from a fresh extraction
"""

import argparse
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TREE = ROOT / "docs" / "ui-concepts" / "canvas" / "project" / "Tree.dc.html"
GAME = ROOT / "src" / "game" / "meta" / "ImmunityTree.cpp"
OUT = ROOT / "assets" / "ui" / "tree_layout.json"

# Canvas glyph names -> icon files (assets/ui/icons, extract_icons.py).
GLYPH_ICONS = {
    "a_cascade": "ability_complement_cascade",
    "a_clot": "ability_fibrin_clot",
    "a_fever": "ability_fever_response",
    "a_histamine": "ability_histamine_flare",
    "t_neutrophil": "tower_neutrophil",
    "t_cytotoxic_t": "tower_cytotoxic_t",
    "t_macrophage": "tower_macrophage",
    "t_goblet_cell": "tower_goblet_cell",
    "t_fibroblast": "tower_fibroblast",
}


def game_keys() -> dict[str, str]:
    """canvas key -> game key"""
    keys = re.findall(r'node\("([a-z_.]+)"', GAME.read_text(encoding="utf-8"))
    return {k.replace(".", "_"): k for k in keys}


def num(v: str) -> float:
    f = float(v)
    return int(f) if f.is_integer() else round(f, 2)


def extract() -> dict:
    s = TREE.read_text(encoding="utf-8")
    to_game = game_keys()

    data = s[s.index("var N = ") + 8:]
    catalog = json.loads(data[:data.index("];") + 1])
    glyph = {n["k"]: n["glyph"] for n in catalog}

    nodes = {}
    for m in re.finditer(r'<button onClick="\{\{h\.([a-z_]+)\}\}"[^>]*style="position: absolute; '
                         r'left: ([\d.]+)px; top: ([\d.]+)px; width: ([\d.]+)px', s):
        key, left, top, size = m.group(1), float(m.group(2)), float(m.group(3)), float(m.group(4))
        g = glyph[key]
        nodes[to_game[key]] = {
            "x": num(left + size / 2), "y": num(top + size / 2), "size": num(size),
            "icon": GLYPH_ICONS.get(g, "stat_" + g),
        }

    # The vessels: the first full-frame svg after the tissue backdrop. Each
    # vessel is a plum wall stroke, then its lumen (a node's {{v.key.vein}}
    # or a fixed colour), then optionally a flowing dash on top.
    start = s.index('<path d="M920 985')
    block = s[start:s.index("</svg>", start)]
    vessels = []
    for m in re.finditer(r'<path( class="anim-flow")? d="([^"]+)" stroke="([^"]+)"(?: stroke-opacity="[^"]+")? '
                         r'stroke-width="([\d.]+)"', block):
        flow, d, stroke, width = m.group(1), m.group(2), m.group(3), float(m.group(4))
        if flow:
            vessels[-1]["flow"] = num(width)
        elif stroke == "#4E1638":
            vessels.append({"d": d, "wall": num(width)})
        else:
            v = vessels[-1]
            v["lumen"] = num(width)
            vein = re.match(r"\{\{v\.([a-z_]+)\.vein\}\}", stroke)
            if vein:
                v["node"] = to_game[vein.group(1)]

    labels = []
    for m in re.finditer(r'<div style="position: absolute; left: ([\d.]+)px; top: ([\d.]+)px; '
                         r'transform: translateX\(-50%\)"><span style="([^"]*)">([^<]*)</span>', s):
        x, y, style, text = float(m.group(1)), float(m.group(2)), m.group(3), html.unescape(m.group(4))
        label = {"x": num(x), "y": num(y), "text": text}
        points = re.match(r"(.*) · \{\{bp\.([A-Za-z]+)\}\}", text)
        if points:
            label["text"] = points.group(1)
            label["style"] = "capstone"
            label["branch"] = points.group(2)
        else:
            label["style"] = "root" if "font-size: 15px" in style else "ability"
        labels.append(label)

    hub = re.search(r'<g transform="translate\(([\d.]+) ([\d.]+)\) scale\(([\d.]+)\) translate', s)
    return {
        "_comment": "Generated by tools/extract_tree_layout.py from the design canvas's Tree artboard; "
                    "canvas pixels of a 1920x1080 frame. Do not edit by hand.",
        "nodes": nodes,
        "vessels": vessels,
        "labels": labels,
        "hub": {"x": num(float(hub.group(1))), "y": num(float(hub.group(2))), "scale": num(float(hub.group(3)))},
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = json.dumps(extract(), indent=1) + "\n"
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"stale: {OUT.relative_to(ROOT)}")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    d = json.loads(text)
    print(f"{OUT.relative_to(ROOT)}: {len(d['nodes'])} nodes, {len(d['vessels'])} vessels, {len(d['labels'])} labels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
